apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: your-dockerhub-user/email-service:latest
          env:
            - name: KAFKA_BROKER
              value: "kafka.kafka.svc.cluster.local:9092"
