apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: your-dockerhub-user/order-service:latest
          env:
            - name: KAFKA_BROKER
              value: "kafka.kafka.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: kafka
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
